# using scikit-learn to do a linear regression...
# importing pandas as pd...
import pandas as pd

# importing matplotlib.pyplot as plt...
import matplotlib.pyplot as plt

# importing LinearRegression from sklearn.linear_model...
from sklearn.linear_model import LinearRegression

# Import data
df = pd.read_csv("https://bit.ly/3go0Ant")

# Input (X)...
X = df.values[:, :-1]

# output (Y)...
Y = df.values[:, -1]

# Train the model...
fit = LinearRegression().fit(X, Y)

# Slope and intercept...
# m = 1.7867224...
m = fit.coef_.flatten()

# b = -16.51923513...
b = fit.intercept_.flatten()

# .format(m) replaces {} with the value stored in the variable m...
print("m = {}".format(m))

# .format(b) replaces {} with the value stored in the variable b...
print("b = {}".format(b))

# Plot data...
# scatterplot...
plt.plot(X, Y, "o")

# line...
plt.plot(X, m*X+b)

# shows...
plt.show()