# calculating m and b for a simple linear regression...
# importing pandas as pd... 
import pandas as pd

# load the data... 
# https//bit.ly/2KF29Bd
# create the dataset...
df = pd.DataFrame({
    "x": [1,2,3,4,5,6,7,8,9,10],
    "y": [5,10,10,15,14,15,19,18,25,23]
})

# extract x and y values...
x = df["x"]
y = df["y"]

# total number of data points...
n = len(df)

# calculate slope m...
m = (n * sum(x * y) - sum(x) * sum(y)) / (n * sum(x**2) - (sum(x))**2)

# calculate intercept b...
b = (sum(y) - m * sum(x)) / n

# print slope m...
print("m =", m)

# prints intercept b...
print("b =", b)
