# calculating the critical value from a T-distribution...
# importing t from scipy.stats... 
from scipy.stats import t

# sample size... 
n = 10

# define lower cumulative value...
lower_cv = t(n-1).ppf(0.025)

# define upper cumulative value...
upper_cv = t(n-1).ppf(0.975)

# printing lower and upper cumulative value...
print(lower_cv, upper_cv)

# testing significance for linear-looking data... 
# importing t from scipy.stats... 
from scipy.stats import t

# importing sqrt from math... 
from math import sqrt

# sample size... 
n = 10

# define lower cumulative value...
lower_cv = t(n-1).ppf(0.025)

# define upper cumulative value...
upper_cv = t(n-1).ppf(0.975)

# correlation coefficient... 
# derive data from https:/bit.ly/2KF29Bd...
r = 0.957586

# perform the test... 
test_value = r / sqrt((1-r**2) / (n-2))

# printing test value...
print("TEST VALUE: {}".format(test_value))

# printing critical range...
print("CRITICAL RANGE: {}, {}". format(lower_cv, upper_cv))

# applies if-else conditions...
# applied if-statments... 
if test_value < lower_cv or test_value > upper_cv:
    
# prints if statement...    
    print("CORRELATION PROVEN, REJECTE HO.\n")

# applied else statement...        
else:
    
# prints else statement...    
    print("CORRELATION NOT PROVEN, FAILED TO REJECT HO.\n")
    
# calculate p-value...
# applies if-else conditions...
# applied if-statments... 
if test_value > 0:
    
# prints if statement...        
    p_value = 1.0 - t(n-1).cdf(test_value)
    
# applied else statement...        
else:
    
# prints else statement...        
    p_value = t(n-1).cdf(test_value)
    
# apply two-tailed test, so multiply by 2...
p_value = p_value * 2

# prints p_value... 
print("P-VALUE: {}". format(p_value))