# using pandas to see the correlation coefficient between every pair of variables...
# importing pandas as pd...
import pandas as pd

# create dataset...
# https://bit.ly/2KF29Bd
df = pd.DataFrame({
    "x": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "y": [5, 10, 10, 15, 14, 15, 19, 18, 25, 23]
})

# derive correlation...
correlations = df.corr(method="pearson")

# prints correlation...
print(correlations)

# calculating correlation coefficient from scratch in python...
# importing pandas as pd...
import pandas as pd

# importing sqrt from math...
from math import sqrt

# Import points from CSV
points = list(pd.read_csv("https://bit.ly/2KF29Bd").itertuples())

# n for length of points...
n = len(points)
# we can use data set method instead of this...

# formulate for numerator...
numerator = n * sum(p.x * p.y for p in points) - \
            sum(p.x for p in points) * sum(p.y for p in points)
            
# formulate for denominator...
denominator = sqrt(n * sum(p.x**2 for p in points) - sum(p.x for p in points)**2) \
              * sqrt(n * sum(p.y**2 for p in points) - sum(p.y for p in points)**2)
              
# derivative correlation...
corr = numerator / denominator

# prints correlation...
print(corr)